name: "jb_faturamento"
version: "1.0.0"

profile: "credentials"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  jb_faturamento:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table

vars:
  dia_fim: "{{ modules.datetime.date.today().strftime('%Y%m%d') }}"
  source_param: "EQTL_MA"
  source_orig: "CCS_MA"

#on-run-start: "ALTER WAREHOUSE wh_cargas_criticas SET WAREHOUSE_SIZE = 'MEDIUM';"
#on-run-end: "ALTER WAREHOUSE wh_cargas_criticas SET WAREHOUSE_SIZE = 'X-SMALL';"
#on-run-end: ["{{ atualiza_ordem() }}", "{{ vlr_cont_delta() }}"]
