CREATE OR REPLACE PROCEDURE PRC_MERGE_ITENS_FATURAMENTO AS
BEGIN

EXECUTE IMMEDIATE 'ALTER SESSION FORCE PARALLEL DML PARALLEL 4';

MERGE /*+ PARALLEL(A) */ INTO  ITENS_FATURAMENTO A
USING ITENS_FATURAMENTO_DELTA B
ON (A.MES_COMPETENCIA = B.MES_COMPETENCIA AND A.DOCUMENTO_CALCULO = B.DOCUMENTO_CALCULO AND A.DOCUMENTO_IMPRESSAO = B.DOCUMENTO_IMPRESSAO)
WHEN NOT MATCHED THEN INSERT (MES_COMPETENCIA,DOCUMENTO_CALCULO,DOCUMENTO_IMPRESSAO,LINHA,SETOR_INDUSTRIAL,CATEGORIA_TARIFA,SUBCLASSE, ITEM_DOCUMENTO,ITEM_ORDENACAO,ESCALAO,INICIO_CALCULO,FIM_CALCULO,TIPO_IMPOSTO,CONSUMO,PRECO,RECEITA,BASE_IMPOSTO,ALIQUOTA,OPERACAO,SUB_OPERACAO,DOMICILIO_FISCAL,FLAG,DATA_DADOS)
VALUES (B.MES_COMPETENCIA,B.DOCUMENTO_CALCULO,B.DOCUMENTO_IMPRESSAO,B.LINHA,B.SETOR_INDUSTRIAL,B.CATEGORIA_TARIFA,B.SUBCLASSE, B.ITEM_DOCUMENTO,B.ITEM_ORDENACAO,B.ESCALAO,B.INICIO_CALCULO,B.FIM_CALCULO,B.TIPO_IMPOSTO,B.CONSUMO,B.PRECO,B.RECEITA,B.BASE_IMPOSTO,B.ALIQUOTA,B.OPERACAO,B.SUB_OPERACAO,B.DOMICILIO_FISCAL,B.FLAG,B.DATA_DADOS)
;

COMMIT;

END PRC_MERGE_ITENS_FATURAMENTO;
