CREATE OR REPLACE PROCEDURE PRC_ATUALIZA_FAT_DELTA_DIA AS
--DECLARE

BEGIN
EXECUTE IMMEDIATE 'ALTER SESSION FORCE PARALLEL DML PARALLEL 4';

--MERGE PARA INSERIR NOVOS REGISTROS E ATUALIZAR ANTIGOS
MERGE /*+ NO_INDEX(A) */ INTO  FATURAMENTO A
USING FATURAMENTO_DELTA B
ON
(
A.MES_COMPETENCIA = B.MES_COMPETENCIA
AND A.DOCUMENTO_CALCULO = B.DOCUMENTO_CALCULO
AND A.DOCUMENTO_IMPRESSAO = B.DOCUMENTO_IMPRESSAO
)
WHEN NOT MATCHED THEN INSERT (MES_COMPETENCIA,MES_REFERENCIA,DOCUMENTO_CALCULO,DOCUMENTO_IMPRESSAO,FATURA,INSTALACAO,CONTA_CONTRATO,PARCEIRO_NEGOCIO,CONTRATO,UNIDADE_LEITURA,ETAPA,SETOR_INDUSTRIAL,GRUPO,CATEGORIA_TARIFA,CLIENTE_LIVRE,SUBCLASSE,MOTIVO_CRIACAO_IMPRESSAO,TIPO_IMPRESSAO,TIPO_CALCULO,ORIGEM_DOCUMENTO,CNR,ESTORNADO,ESTORNO_PLENO,ESTORNO_AJUSTE,REVERSAO,CANCELAMENTO,FATURA_VIRTUAL,MINIMO,DOCUMENTO_ESTORNO_PLENO,DATA_ESTORNO_PLENO,MOTIVO_ESTORNO_PLENO,DOCUMENTO_ESTORNO_AJUSTE,DATA_ESTORNO_AJUSTE,MOTIVO_ESTORNO_AJUSTE,VALOR_FATURA,VALOR_CONTABIL,CONSUMO_FATURADO,CONSUMO_MEDIDO,EUSD,EUSDB,ICMS,ICMS_SUBVENCAO,PIS,COFINS,CIP,RETENCAO,RECEITA_BANDEIRAS,RECEITA_CONSUMO_FATURADO,TARIFA,PRECO,CORRECAO_MONETARIA,CREDITOS,ESTORNOS,JUROS,MULTAS,PARCELAMENTOS,OUTROS_LANCAMENTOS,CHAVE_RECONCILIACAO,FORMULARIO_PAGAMENTO,DOMICILIO_FISCAL,INICIO_CALCULO,FIM_CALCULO,QUANTIDADE_DIAS,DATA_COMPETENCIA,DATA_ATRIBUICAO_CALCULO,DATA_APRESENTACAO,DATA_VENCIMENTO_ORIGINAL,DATA_PREVISAO_LEITURA,DATA_CRIACAO_IMPRESSAO,USUARIO_CRIACAO_IMPRESSAO,DATA_MODIFICACAO_IMPRESSAO,USUARIO_MODIFICACAO_IMPRESSAO,DATA_CRIACAO_CALCULO,USUARIO_CRIACAO_CALCULO,DATA_MODIFICACAO_CALCULO,USUARIO_MODIFICACAO_CALCULO,DOCUMENTO_CALCULO_ANTERIOR,ESTRUTURA_REGIONAL_POLITICA,ORDEM_FATURAMENTO, DATA_DADOS, CONSUMO_REGISTRADO)
VALUES (B.MES_COMPETENCIA,B.MES_REFERENCIA,B.DOCUMENTO_CALCULO,B.DOCUMENTO_IMPRESSAO,B.FATURA,B.INSTALACAO,B.CONTA_CONTRATO,B.PARCEIRO_NEGOCIO,B.CONTRATO,B.UNIDADE_LEITURA,B.ETAPA,B.SETOR_INDUSTRIAL,B.GRUPO,B.CATEGORIA_TARIFA,B.CLIENTE_LIVRE,B.SUBCLASSE,B.MOTIVO_CRIACAO_IMPRESSAO,B.TIPO_IMPRESSAO,B.TIPO_CALCULO,B.ORIGEM_DOCUMENTO,B.CNR,B.ESTORNADO,B.ESTORNO_PLENO,B.ESTORNO_AJUSTE,B.REVERSAO,B.CANCELAMENTO,B.FATURA_VIRTUAL,B.MINIMO,B.DOCUMENTO_ESTORNO_PLENO,B.DATA_ESTORNO_PLENO,B.MOTIVO_ESTORNO_PLENO,B.DOCUMENTO_ESTORNO_AJUSTE,B.DATA_ESTORNO_AJUSTE,B.MOTIVO_ESTORNO_AJUSTE,B.VALOR_FATURA,B.VALOR_CONTABIL,B.CONSUMO_FATURADO,B.CONSUMO_MEDIDO,B.EUSD,B.EUSDB,B.ICMS,B.ICMS_SUBVENCAO,B.PIS,B.COFINS,B.CIP,B.RETENCAO,B.RECEITA_BANDEIRAS,B.RECEITA_CONSUMO_FATURADO,B.TARIFA,B.PRECO,B.CORRECAO_MONETARIA,B.CREDITOS,B.ESTORNOS,B.JUROS,B.MULTAS,B.PARCELAMENTOS,B.OUTROS_LANCAMENTOS,B.CHAVE_RECONCILIACAO,B.FORMULARIO_PAGAMENTO,B.DOMICILIO_FISCAL,B.INICIO_CALCULO,B.FIM_CALCULO,B.QUANTIDADE_DIAS,B.DATA_COMPETENCIA,B.DATA_ATRIBUICAO_CALCULO,B.DATA_APRESENTACAO,B.DATA_VENCIMENTO_ORIGINAL,B.DATA_PREVISAO_LEITURA,B.DATA_CRIACAO_IMPRESSAO,B.USUARIO_CRIACAO_IMPRESSAO,B.DATA_MODIFICACAO_IMPRESSAO,B.USUARIO_MODIFICACAO_IMPRESSAO,B.DATA_CRIACAO_CALCULO,B.USUARIO_CRIACAO_CALCULO,B.DATA_MODIFICACAO_CALCULO,B.USUARIO_MODIFICACAO_CALCULO,B.DOCUMENTO_CALCULO_ANTERIOR,B.ESTRUTURA_REGIONAL_POLITICA,B.ORDEM_FATURAMENTO, B.DATA_DADOS, B.CONSUMO_REGISTRADO)
;

COMMIT;

--MERGE PARA INSERIR NOVOS REGISTROS E ATUALIZAR ANTIGOS ESTORNOS
MERGE /*+ NO_INDEX(A) */ INTO  FATURAMENTO A
USING TMP_ESTORNADOS_DELTA B
ON
(
A.MES_COMPETENCIA = B.MES_COMPETENCIA
AND A.DOCUMENTO_CALCULO = B.DOCUMENTO_CALCULO
AND A.DOCUMENTO_IMPRESSAO = B.DOCUMENTO_IMPRESSAO
)
WHEN MATCHED THEN UPDATE SET
A.MOTIVO_CRIACAO_IMPRESSAO = B.MOTIVO_CRIACAO_IMPRESSAO,
A.ESTORNADO = B.ESTORNADO,
A.ESTORNO_PLENO = B.ESTORNO_PLENO,
A.ESTORNO_AJUSTE = B.ESTORNO_AJUSTE,
A.REVERSAO = B.REVERSAO,
A.CANCELAMENTO = B.CANCELAMENTO,
A.FATURA_VIRTUAL = B.FATURA_VIRTUAL,
A.DOCUMENTO_ESTORNO_PLENO = B.DOCUMENTO_ESTORNO_PLENO,
A.DATA_ESTORNO_PLENO = B.DATA_ESTORNO_PLENO,
A.MOTIVO_ESTORNO_PLENO = B.MOTIVO_ESTORNO_PLENO,
A.DOCUMENTO_ESTORNO_AJUSTE = B.DOCUMENTO_ESTORNO_AJUSTE,
A.DATA_ESTORNO_AJUSTE = B.DATA_ESTORNO_AJUSTE,
A.MOTIVO_ESTORNO_AJUSTE = B.MOTIVO_ESTORNO_AJUSTE,
A.VALOR_CONTABIL = B.VALOR_CONTABIL,
A.DATA_CRIACAO_IMPRESSAO = B.DATA_CRIACAO_IMPRESSAO,
A.USUARIO_CRIACAO_IMPRESSAO = B.USUARIO_CRIACAO_IMPRESSAO,
A.DATA_MODIFICACAO_IMPRESSAO = B.DATA_MODIFICACAO_IMPRESSAO,
A.USUARIO_MODIFICACAO_IMPRESSAO = B.USUARIO_MODIFICACAO_IMPRESSAO,
A.DATA_CRIACAO_CALCULO = B.DATA_CRIACAO_CALCULO,
A.USUARIO_CRIACAO_CALCULO = B.USUARIO_CRIACAO_CALCULO,
A.DATA_MODIFICACAO_CALCULO = B.DATA_MODIFICACAO_CALCULO,
A.USUARIO_MODIFICACAO_CALCULO = B.USUARIO_MODIFICACAO_CALCULO,
A.ORDEM_FATURAMENTO = B.ORDEM_FATURAMENTO,
A.DATA_DADOS = B.DATA_DADOS

WHEN NOT MATCHED THEN INSERT (MES_COMPETENCIA,MES_REFERENCIA,DOCUMENTO_CALCULO,DOCUMENTO_IMPRESSAO,FATURA,INSTALACAO,CONTA_CONTRATO,PARCEIRO_NEGOCIO,CONTRATO,UNIDADE_LEITURA,ETAPA,SETOR_INDUSTRIAL,GRUPO,CATEGORIA_TARIFA,CLIENTE_LIVRE,SUBCLASSE,MOTIVO_CRIACAO_IMPRESSAO,TIPO_IMPRESSAO,TIPO_CALCULO,ORIGEM_DOCUMENTO,CNR,ESTORNADO,ESTORNO_PLENO,ESTORNO_AJUSTE,REVERSAO,CANCELAMENTO,FATURA_VIRTUAL,MINIMO,DOCUMENTO_ESTORNO_PLENO,DATA_ESTORNO_PLENO,MOTIVO_ESTORNO_PLENO,DOCUMENTO_ESTORNO_AJUSTE,DATA_ESTORNO_AJUSTE,MOTIVO_ESTORNO_AJUSTE,VALOR_FATURA,VALOR_CONTABIL,CONSUMO_FATURADO,CONSUMO_MEDIDO,EUSD,EUSDB,ICMS,ICMS_SUBVENCAO,PIS,COFINS,CIP,RETENCAO,RECEITA_BANDEIRAS,RECEITA_CONSUMO_FATURADO,TARIFA,PRECO,CORRECAO_MONETARIA,CREDITOS,ESTORNOS,JUROS,MULTAS,PARCELAMENTOS,OUTROS_LANCAMENTOS,CHAVE_RECONCILIACAO,FORMULARIO_PAGAMENTO,DOMICILIO_FISCAL,INICIO_CALCULO,FIM_CALCULO,QUANTIDADE_DIAS,DATA_COMPETENCIA,DATA_ATRIBUICAO_CALCULO,DATA_APRESENTACAO,DATA_VENCIMENTO_ORIGINAL,DATA_PREVISAO_LEITURA,DATA_CRIACAO_IMPRESSAO,USUARIO_CRIACAO_IMPRESSAO,DATA_MODIFICACAO_IMPRESSAO,USUARIO_MODIFICACAO_IMPRESSAO,DATA_CRIACAO_CALCULO,USUARIO_CRIACAO_CALCULO,DATA_MODIFICACAO_CALCULO,USUARIO_MODIFICACAO_CALCULO,DOCUMENTO_CALCULO_ANTERIOR,ESTRUTURA_REGIONAL_POLITICA,ORDEM_FATURAMENTO, DATA_DADOS, CONSUMO_REGISTRADO)
VALUES (B.MES_COMPETENCIA,B.MES_REFERENCIA,B.DOCUMENTO_CALCULO,B.DOCUMENTO_IMPRESSAO,B.FATURA,B.INSTALACAO,B.CONTA_CONTRATO,B.PARCEIRO_NEGOCIO,B.CONTRATO,B.UNIDADE_LEITURA,B.ETAPA,B.SETOR_INDUSTRIAL,B.GRUPO,B.CATEGORIA_TARIFA,B.CLIENTE_LIVRE,B.SUBCLASSE,B.MOTIVO_CRIACAO_IMPRESSAO,B.TIPO_IMPRESSAO,B.TIPO_CALCULO,B.ORIGEM_DOCUMENTO,B.CNR,B.ESTORNADO,B.ESTORNO_PLENO,B.ESTORNO_AJUSTE,B.REVERSAO,B.CANCELAMENTO,B.FATURA_VIRTUAL,B.MINIMO,B.DOCUMENTO_ESTORNO_PLENO,B.DATA_ESTORNO_PLENO,B.MOTIVO_ESTORNO_PLENO,B.DOCUMENTO_ESTORNO_AJUSTE,B.DATA_ESTORNO_AJUSTE,B.MOTIVO_ESTORNO_AJUSTE,B.VALOR_FATURA,B.VALOR_CONTABIL,B.CONSUMO_FATURADO,B.CONSUMO_MEDIDO,B.EUSD,B.EUSDB,B.ICMS,B.ICMS_SUBVENCAO,B.PIS,B.COFINS,B.CIP,B.RETENCAO,B.RECEITA_BANDEIRAS,B.RECEITA_CONSUMO_FATURADO,B.TARIFA,B.PRECO,B.CORRECAO_MONETARIA,B.CREDITOS,B.ESTORNOS,B.JUROS,B.MULTAS,B.PARCELAMENTOS,B.OUTROS_LANCAMENTOS,B.CHAVE_RECONCILIACAO,B.FORMULARIO_PAGAMENTO,B.DOMICILIO_FISCAL,B.INICIO_CALCULO,B.FIM_CALCULO,B.QUANTIDADE_DIAS,B.DATA_COMPETENCIA,B.DATA_ATRIBUICAO_CALCULO,B.DATA_APRESENTACAO,B.DATA_VENCIMENTO_ORIGINAL,B.DATA_PREVISAO_LEITURA,B.DATA_CRIACAO_IMPRESSAO,B.USUARIO_CRIACAO_IMPRESSAO,B.DATA_MODIFICACAO_IMPRESSAO,B.USUARIO_MODIFICACAO_IMPRESSAO,B.DATA_CRIACAO_CALCULO,B.USUARIO_CRIACAO_CALCULO,B.DATA_MODIFICACAO_CALCULO,B.USUARIO_MODIFICACAO_CALCULO,B.DOCUMENTO_CALCULO_ANTERIOR,B.ESTRUTURA_REGIONAL_POLITICA,B.ORDEM_FATURAMENTO, B.DATA_DADOS, B.CONSUMO_REGISTRADO)
;

COMMIT;

END PRC_ATUALIZA_FAT_DELTA_DIA;
