SELECT
    belnr AS DOCUMENTO_CALCULO,
    belzart AS ITEM_DOCUMENTO,
    VERTRAG AS CONTRATO,
    ANLAGE AS INSTALACAO,
    CASE 
        WHEN ZCFAT_IRREG_INF.ADAT = '00000000' THEN NULL
        ELSE TO_DATE(ZCFAT_IRREG_INF.ADAT, 'YYYYMMDD')
    END DATA_LEITURA,
    "status",
    CASE 
        WHEN ZCFAT_IRREG_INF.INVOICED = ' ' THEN NULL
        ELSE ZCFAT_IRREG_INF.INVOICED
    END FLAG,
    CASE 
        WHEN ZCFAT_IRREG_INF.GRUPO_ESTIM = ' ' THEN NULL
        ELSE ZCFAT_IRREG_INF.GRUPO_ESTIM
    END TIPO_ESTIMATIVA,
    QTDE_DIAS AS TOTAL_DIAS_PERIODO,
    QTDE_DIAS_FAT AS TOTAL_DIAS_FATURADO,
    QTDE_DIAS_NFAT AS TOTAL_DIAS_NAO_FATURADO,
    QTDE_FATURAS AS TOTAL_FATURAS,
    CONS_TOTAL AS CONSUMO_TOTAL,
    CONS_DIARIO AS CONSUMO_DIARIO,
    CONS_FATURADO AS CONSUMO_FATURADO,
    CONS_ATUAL AS CONSUMO_ATUAL,
    CONS_AJUSTE AS CONSUMO_AJUSTE,
    CONS_MEDIA AS CONSUMO_MEDIA,
    CONS_DIFERENCA AS CONSUMO_DIFERENCA,
    CONS_DIA_COMPLEMENTO AS CONSUMO_DIA_COMPLEMENTO,
    CONS_FAT_COMPLEMENTO AS CONSUMO_FAT_COMPLEMENTO,
    CONS_NAO_FATURADO AS CONSUMO_NAO_FATURADO,
    CASE 
        WHEN ZCFAT_IRREG_INF.DATA_LEI_ANTERIOR = '00000000' THEN NULL
        ELSE TO_DATE(ZCFAT_IRREG_INF.DATA_LEI_ANTERIOR, 'YYYYMMDD')
    END DATA_LEITURA_ANTERIOR,
    LEIT_ANTERIOR AS LEITURA_ANTERIOR,
    PARCELAS,
    AJUS_USER AS OPERANDO,
    CASE 
        WHEN ZCFAT_IRREG_INF.RPNUM = ' ' THEN NULL
        ELSE ZCFAT_IRREG_INF.RPNUM
    END NUMERO_DOCUMENTO
FROM
    {{ ref ('stg_zcfat_irreg_inf')}} AS ZCFAT_IRREG_INF
WHERE
    MANDT IN (401, 402, 403, 404)
