{{
  config(
    materialized = 'incremental',
    incremental_strategy = 'merge_insert_only',
    unique_key = ['mes_competencia', 'documento_calculo', 'documento_impressao'],
    post_hook = ["{{ merge_estornados() }}","{{ update_reversao() }}"],
    )
}}

select
    mes_competencia,
    mes_referencia,
    documento_calculo,
    documento_impressao,
    fatura,
    instalacao,
    conta_contrato,
    parceiro_negocio,
    contrato,
    unidade_leitura,
    etapa,
    setor_industrial,
    grupo,
    categoria_tarifa,
    cliente_livre,
    subclasse,
    motivo_criacao_impressao,
    tipo_impressao,
    tipo_calculo,
    origem_documento,
    cnr,
    estornado,
    estorno_pleno,
    estorno_ajuste,
    reversao,
    cancelamento,
    fatura_virtual,
    minimo,
    documento_estorno_pleno,
    motivo_estorno_pleno,
    documento_estorno_ajuste,
    motivo_estorno_ajuste,
    valor_fatura,
    valor_contabil,
    consumo_faturado,
    consumo_medido,
    eusd,
    icms,
    icms_subvencao,
    pis,
    cofins,
    cip,
    retencao,
    receita_bandeiras,
    receita_consumo_faturado,
    tarifa,
    preco,
    correcao_monetaria,
    creditos,
    estornos,
    juros,
    multas,
    parcelamentos,
    outros_lancamentos,
    formulario_pagamento,
    domicilio_fiscal,
    documento_calculo_anterior,
    estrutura_regional_politica,
    eusdb,
    CAST(data_estorno_pleno as TIMESTAMP_NTZ(0)) as data_estorno_pleno,
    CAST(data_estorno_ajuste as TIMESTAMP_NTZ(0)) as data_estorno_ajuste,
    CAST(chave_reconciliacao as VARCHAR(12)) as chave_reconciliacao,
    CAST(inicio_calculo as TIMESTAMP_NTZ(0)) as inicio_calculo,
    CAST(fim_calculo as TIMESTAMP_NTZ(0)) as fim_calculo,
    CAST(quantidade_dias as NUMBER(38, 0)) as quantidade_dias,
    CAST(data_competencia as TIMESTAMP_NTZ(0)) as data_competencia,
    CAST(data_atribuicao_calculo as TIMESTAMP_NTZ(0))
        as data_atribuicao_calculo,
    CAST(data_apresentacao as TIMESTAMP_NTZ(0)) as data_apresentacao,
    CAST(data_vencimento_original as TIMESTAMP_NTZ(0))
        as data_vencimento_original,
    CAST(data_previsao_leitura as TIMESTAMP_NTZ(0)) as data_previsao_leitura,
    CAST(data_criacao_impressao as TIMESTAMP_NTZ(0)) as data_criacao_impressao,
    CAST(usuario_criacao_impressao as VARCHAR(12)) as usuario_criacao_impressao,
    CAST(data_modificacao_impressao as TIMESTAMP_NTZ(0))
        as data_modificacao_impressao,
    CAST(usuario_modificacao_impressao as VARCHAR(12))
        as usuario_modificacao_impressao,
    CAST(data_criacao_calculo as TIMESTAMP_NTZ(0)) as data_criacao_calculo,
    CAST(usuario_criacao_calculo as VARCHAR(12)) as usuario_criacao_calculo,
    CAST(data_modificacao_calculo as TIMESTAMP_NTZ(0))
        as data_modificacao_calculo,
    CAST(usuario_modificacao_calculo as VARCHAR(12))
        as usuario_modificacao_calculo,
    CAST(data_dados as TIMESTAMP_NTZ(0)) as data_dados,
    CAST(ordem_faturamento as NUMBER(38, 0)) as ordem_faturamento,
    CAST(consumo_registrado as NUMBER(28, 14)) as consumo_registrado
{{ colunas_faturamento_pial(var('source_param')) }}
from {{ ref ('faturamento_delta') }}
