{{
  config(
    materialized = 'incremental',
    incremental_strategy = 'merge_insert_only',
    unique_key = ['mes_competencia', 'documento_calculo', 'documento_impressao'],
    post_hook = ["{{ merge_estornados() }}","{{ update_reversao() }}"],
    )
}}

SELECT
    mes_competencia,
    mes_referencia,
    documento_calculo,
    documento_impressao,
    fatura,
    instalacao,
    conta_contrato,
    parceiro_negocio,
    contrato,
    unidade_leitura,
    etapa,
    setor_industrial,
    grupo,
    categoria_tarifa,
    cliente_livre,
    subclasse,
    motivo_criacao_impressao,
    tipo_impressao,
    tipo_calculo,
    origem_documento,
    cnr,
    estornado,
    estorno_pleno,
    estorno_ajuste,
    reversao,
    cancelamento,
    fatura_virtual,
    minimo,
    documento_estorno_pleno,
    CAST(DATA_ESTORNO_PLENO AS TIMESTAMP_NTZ(0)) AS DATA_ESTORNO_PLENO,
    motivo_estorno_pleno,
    documento_estorno_ajuste,
    CAST(DATA_ESTORNO_AJUSTE AS TIMESTAMP_NTZ(0)) AS DATA_ESTORNO_AJUSTE,
    motivo_estorno_ajuste,
    valor_fatura,
    valor_contabil,
    consumo_faturado,
    consumo_medido,
    eusd,
    icms,
    icms_subvencao,
    pis,
    cofins,
    cip,
    retencao,
    receita_bandeiras,
    receita_consumo_faturado,
    tarifa,
    preco,
    correcao_monetaria,
    creditos,
    estornos,
    juros,
    multas,
    parcelamentos,
    outros_lancamentos,
    CAST(CHAVE_RECONCILIACAO AS VARCHAR(12)) AS CHAVE_RECONCILIACAO,
    formulario_pagamento,
    domicilio_fiscal,
    CAST(INICIO_CALCULO AS TIMESTAMP_NTZ(0)) AS INICIO_CALCULO,
    CAST(FIM_CALCULO AS TIMESTAMP_NTZ(0)) AS FIM_CALCULO,
    CAST(QUANTIDADE_DIAS AS NUMBER(38,0)) AS QUANTIDADE_DIAS,
    CAST(DATA_COMPETENCIA AS TIMESTAMP_NTZ(0)) AS DATA_COMPETENCIA,
    CAST(DATA_ATRIBUICAO_CALCULO AS TIMESTAMP_NTZ(0)) AS DATA_ATRIBUICAO_CALCULO,
    CAST(DATA_APRESENTACAO AS TIMESTAMP_NTZ(0)) AS DATA_APRESENTACAO,
    CAST(DATA_VENCIMENTO_ORIGINAL AS TIMESTAMP_NTZ(0)) AS DATA_VENCIMENTO_ORIGINAL,
    CAST(DATA_PREVISAO_LEITURA AS TIMESTAMP_NTZ(0)) AS DATA_PREVISAO_LEITURA,
    CAST(DATA_CRIACAO_IMPRESSAO AS TIMESTAMP_NTZ(0)) AS DATA_CRIACAO_IMPRESSAO,
    CAST(USUARIO_CRIACAO_IMPRESSAO AS VARCHAR(12)) AS USUARIO_CRIACAO_IMPRESSAO,
    CAST(DATA_MODIFICACAO_IMPRESSAO AS TIMESTAMP_NTZ(0)) AS DATA_MODIFICACAO_IMPRESSAO,
    CAST(USUARIO_MODIFICACAO_IMPRESSAO AS VARCHAR(12)) AS USUARIO_MODIFICACAO_IMPRESSAO,
    CAST(DATA_CRIACAO_CALCULO AS TIMESTAMP_NTZ(0)) AS DATA_CRIACAO_CALCULO,
    CAST(USUARIO_CRIACAO_CALCULO AS VARCHAR(12)) AS USUARIO_CRIACAO_CALCULO,
    CAST(DATA_MODIFICACAO_CALCULO AS TIMESTAMP_NTZ(0)) AS DATA_MODIFICACAO_CALCULO,
    CAST(USUARIO_MODIFICACAO_CALCULO AS VARCHAR(12)) AS USUARIO_MODIFICACAO_CALCULO,
    documento_calculo_anterior,
    estrutura_regional_politica,
    CAST(DATA_DADOS AS TIMESTAMP_NTZ(0)) AS DATA_DADOS,
    CAST(ORDEM_FATURAMENTO AS NUMBER(38,0)) AS ORDEM_FATURAMENTO,
    CAST(CONSUMO_REGISTRADO AS NUMBER(28,14)) AS CONSUMO_REGISTRADO,
    eusdb
FROM {{ ref ('faturamento_delta') }}
