SELECT
    A.ANLAGE AS INSTALACAO, 
    TO_DATE(TO_DATE(A.ABRDATS, 'YYYYMMDD')) AS DATA_CALC_PREVISTO, 
    A.ABRVORG AS TIPO_CALCULO,
    CASE 
        WHEN A.TRIGSTAT = '1' THEN 'NAO_CALCULAVEL'
        WHEN A.TRIGSTAT = '2' THEN 'CALCULAVEL'
    END AS "STATUS",
    A.ABLEINH UL,
    TO_DATE(TO_DATE(A.ERDAT, 'YYYYMMDD')) AS DATA_CRIACAO,
    A.ERNAM AS CRIADO_POR
FROM 
    {{ref ('stg_etrg')}} A

